language: java
before_script:
 - psql -c "create database datapopulator;" -U postgres;psql -c "create role datapopulator with login password 'letmein'" -U postgres
 #ls;whoami;cd ..;ls -l;pwd;cd ..;ls -l;
